framework:
    mailer:
        envelope:
            sender: 'robot@ranked-choice.com'
        headers:
            from: 'Robot <robot@ranked-choice.com>'
        dsn: '%env(MAILER_DSN)%'
        #dsn: 'null://null'
