version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo apt install libpng-dev libpq-dev libxslt1.1 libxslt1-dev
      - run: sudo docker-php-ext-install zip gd pgsql xsl

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: "Create Environment file"
          command: mv .env.test .env

      - run:
          name: "Create Build folder"
          command: mkdir ./public/build

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn run build

      - run: php bin/console doctrine:database:drop --force || true
      - run: php bin/console doctrine:database:create
      - run: php bin/console doctrine:migrations:migrate -n
      - run: php bin/console doctrine:schema:update --force
      - run: php bin/console hautelook:fixtures:load -n
      - run: php ./vendor/bin/phpunit
