#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#homepage:
#  path: /{_locale}
#  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#  requirements:
#    _locale: '%app_locales%'
#  defaults:
#    template: main/shop/index.html.twig
#    _locale: '%locale%'

index:
   path: /
   defaults:
      _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
      path: '/%locale%'
      permanent: true
