version: '3.3'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: rc_admin
      POSTGRES_PASSWORD: rc1234
      POSTGRES_DB: ranked_choice
    ports:
      - 15432:5432
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    depends_on:
      - db
    environment:
      #- APP_ENV=dev
      - DATABASE_URL=postgresql://rc_admin:rc1234@db:5432/ranked_choice?serverVersion=12.5&charset=utf8
      #- COMPOSER_MEMORY_LIMIT=512M
    volumes:
      - ../:/var/www
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
